### PR TITLE
Initial configuration for Travis CI

### PR DESCRIPTION
**Pull request by slivingston**
This pull request introduces a small configuration for using [Travis CI](https://travis-ci.org). It does nothing more than perform `pip install .`. In particular, OpenCV is not installed. Nonetheless I open this PR as a first introduction of using Travis CI with `webcam-streamer`.

Remaining concerns, which can be addressed here or in another pull request:

1. Should Python 2.6 and Python 3.2 be supported? Note that version 2.6 is not being maintained anymore (cf. <https://www.python.org/dev/peps/pep-0361/#release-lifespan>), and the nominal lifespan of upstream maintenance of version 3.2 is also past (cf. <https://www.python.org/dev/peps/pep-0392/#lifespan>).

2. I did not find tests in the repository. After this PR, I want to at least create a trivial test that can catch the import error reported in #8.

### CODE REVIEW

**Comment by slivingston** [comment]
For example, the build on Travis CI that was performed for the current tip of this PR is <https://travis-ci.org/slivingston/webcam-streamer/builds/218319441>. Notice that jobs succeeded for all versions of Python except 2.6 and 3.2.

**Comment by theopolisme** [comment]
Hi & thanks very much for making this pull request! I really appreciate it - Travis integration would definitely be helpful.

Re your question about 2.6/3.2, I don't particularly see any reason to support them - as you said, they're functionally EOL. At minimum you'd expect someone to be running 2.7.

If you remove those from the build config (and from `setup.py`) I'd be happy to merge this and get it running automatically on commit!

Thanks again!

**Comment by slivingston** [comment]
done.

**Comment by theopolisme** [comment]
Perfect, thank you! I've gone ahead and merged this PR.
Configuring the Travis integration now...

**Pull request merged**
